import { type NextPage } from "next";
import { signIn } from 'next-auth/react';
import Head from "next/head";

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>Drawaday | Log in  </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        Login
        <a href="/api/auth/signin"
           onClick={(e) => {
           e.preventDefault()
           signIn()
        }}>You must be signed in to view this page</a>
      </main>
    </>
  );
};

export default Login;
