import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import BottomNavigation from "../components/BottomNavigation";

const Profile: NextPage = () => {

  return (
    <>
      <Head>
        <title>Drawaday | Profile </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        Profile
      </main>
      <BottomNavigation currentPage="Profile"></BottomNavigation>
    </>
  );
};

export default Profile;
